services:
  cakeshopdb:
    image: mysql:8.0
    container_name: cakeshopdb
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Phuongngarootpassword
      MYSQL_DATABASE: cake_shop
      MYSQL_USER: phuongnga
      MYSQL_PASSWORD: phuongnga10019995
    volumes:
      - cakeshop_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

  server:
    build: .
    container_name: spring-boot-app
    restart: always
    ports:
      - "9090:8080"
    environment:
      DB_NAME: cake_shop
      DB_URL: cakeshopdb
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: Phuongngarootpassword
    depends_on:
      - cakeshopdb

volumes:
  cakeshop_data:

networks:
  cakeshop_network:
      